### ISSUE TITLE
Error when running arbot

### ISSUE THREAD

**Issue by bylren001** [jr-minnaar/bitrader#5]
Hi,

I have installed everything and updated the .env file with relevant api's tokens. When running arbot I get the following errors:

Traceback (most recent call last):
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/connector.py", line 797, in _wrap_create_connection
    return (yield from self._loop.create_connection(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 802, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 828, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/telepot/aio/api.py", line 139, in request
    async with fn(*args, **kwargs) as r:
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/connector.py", line 402, in connect
    proto = yield from self._create_connection(req)
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/connector.py", line 749, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/connector.py", line 860, in _create_direct_connection
    raise last_exc
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/connector.py", line 832, in _create_direct_connection
    req=req, client_error=client_error)
  File "/Users/renebaylisswork/Downloads/bitrader-master/venv/lib/python3.6/site-packages/aiohttp/connector.py", line 802, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host api.telegram.org:443 ssl:True [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)]

Any thoughts on this?

Thanks

Rene

**Comment by ayeseadewale** [comment]
Error.... 
Traceback (most recent call last):
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\loop.py", line 29, in run_forever
    result = await self._bot.getUpdates(offset=offset,
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 587, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 78, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\api.py", line 146, in request
    return await _parse(r)
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\api.py", line 132, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
Traceback (most recent call last):
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\loop.py", line 29, in run_forever
    result = await self._bot.getUpdates(offset=offset,
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 587, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 78, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\api.py", line 146, in request
    return await _parse(r)
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\api.py", line 132, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
Traceback (most recent call last):
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\loop.py", line 29, in run_forever
    result = await self._bot.getUpdates(offset=offset,
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 587, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 78, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\api.py", line 146, in request
    return await _parse(r)
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\api.py", line 132, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
Traceback (most recent call last):
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\loop.py", line 29, in run_forever
    result = await self._bot.getUpdates(offset=offset,
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 587, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\__init__.py", line 78, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "c:\users\ayese\appdata\local\programs\python\python39\lib\site-packages\telepot\aio\api.py", line 146, in request
    return await _parse(r)
